### ISSUE TITLE
TypeError: require(...).tmpDir is not a function

### ISSUE THREAD

**Issue by timsayshey** [wayneashleyberry/devotions-cli#3]
Looked forward to trying this out but it's not working. I'm using Node v14.2.0.

```
~ % devotion
/usr/local/lib/node_modules/devotions-cli/node_modules/cache-swap/index.js:9
var tmpDir = require('os').tmpDir();
                           ^
TypeError: require(...).tmpDir is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/devotions-cli/node_modules/cache-swap/index.js:9:28)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/devotions-cli/lib/cache.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
```

**Comment by wayneashleyberry** [comment]
Hey @timsayshey, I had a look into this and could upgrade all the internal dependencies... but it turns out the API this relies on doesn't exist any more 😢
